"""empty message

Revision ID: 4554010b3fcf
Revises: 
Create Date: 2020-09-04 21:13:54.774001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4554010b3fcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###
